Repository SkyFlyTeam/BeeOnTime-frontend, pull requests merged in 2025-05, with the labels that each got.

#165 hotfix: tirando o nome no email
  src/pages/admin/page.tsx
  src/utils/emails/PrimeiroAcesso.tsx
Labels: PR Aprovado

#125 Hotfix/ajuste banco horas
  src/components/custom/TablePagination/TablePagination.tsx
  src/components/ui/datatable.tsx
  src/interfaces/jornada.ts
  src/pages/bancoHoras/[id].tsx
  src/pages/bancoHoras/columns.tsx
  src/pages/bancoHoras/index.tsx
  src/services/relatorioBancoHoras.ts
  src/utils/functions/verifyWorkDay.ts
Labels: bug, PR Aprovado

#116 hotfix: Colaborador ADM/Gestor nao mais na própria lista
  src/pages/colaboradores/index.tsx
Labels: PR Aprovado

#129 refactor: Removido linhas de 'alert' de debug
  src/components/custom/CardEditarFuncionario/editarFuncionarioForm.tsx
  src/pages/historico-ponto/[id].tsx
  src/services/authService.ts
  src/services/usuarioServices.ts
Labels: PR Aprovado

#168 Feat/tela pontos diarios
  src/components/custom/Sidebar/app-sidebar.tsx
  src/components/custom/flag/index.tsx
  src/components/custom/flag/styles.module.css
  src/components/custom/modalSolicitacao/modalEnvioSolicitacaoFalta/index.tsx
  src/components/ui/custom/datatablePDiarios.tsx
  src/interfaces/pontoDiario.ts
  src/lib/permissions.ts
  src/pages/inicio.tsx
  src/pages/inicioFuncionario/index.tsx
  src/pages/pontosDiarios/columns.tsx
  src/pages/pontosDiarios/components/pontoDiarios.tsx
  src/pages/pontosDiarios/index.tsx
  src/services/relatorioPontoDiarioServices.ts
Labels: enhancement, PR Aprovado

#123 Hotfix: Correções na página de histórico de pontos
  package-lock.json
  package.json
  src/components/custom/histPonto/points-history-table.tsx
Labels: task, PR Aprovado

#122 hotfix: solicitações do mesmo dia e do mesmo tipo agora são bloqueadas
  src/services/solicitacaoServices.ts
Labels: bug, PR Aprovado

#170 Feat/card feriado
  src/interfaces/FeriadoItem.ts
  src/interfaces/feriado.ts
  src/pages/inicioFuncionario/_components/cardFeriado/cardFeriado.tsx
  src/pages/inicioFuncionario/_components/cardFeriado/feriadoItem.tsx
  src/pages/inicioFuncionario/index.tsx
  src/services/feriadoService.ts
Labels: enhancement, PR Aprovado

#174 Feat/editar jornada
  package-lock.json
  package.json
  src/components/custom/CardEditarFuncionario/editarFuncionarioForm.tsx
  src/components/custom/CardEditarJornada/editarJornadaForm.tsx
  src/components/custom/histPonto/points-history-table.tsx
  src/components/ui/radio-group.tsx
  src/components/ui/toggle-group.tsx
  src/components/ui/toggle.tsx
  src/lib/permissions.ts
  src/pages/colaboradores/index.tsx
  src/pages/jornada/[id].tsx
  src/pages/jornada/index.tsx
  src/services/usuarioServices.ts
Labels: PR Aprovado
