Repository SkyFlyTeam/BeeOnTime-frontend, pull requests merged in 2025-04, with the labels that each got.

#51 Hotfix/jornada flexivel
  package-lock.json
  src/components/CadastroJornada.tsx
  src/components/custom/app-sidebar.tsx
  src/components/custom/nav-secondary.tsx
  src/components/ui/sidebar.tsx
  src/enums/tipoPonto.ts
  src/pages/inicio.tsx
  src/pages/inicioFuncionario/_components/cardCargaHoraria/index.tsx
  src/pages/inicioFuncionario/_components/cardCargaHoraria/styles.module.css
  src/pages/inicioFuncionario/_components/time-clock-service.tsx
  src/pages/inicioFuncionario/_components/time-clock.tsx
  src/pages/inicioFuncionario/_components/timeClock/time-clock-service.tsx
  src/pages/inicioFuncionario/_components/timeClock/time-clock.tsx
  src/pages/inicioFuncionario/index.tsx
  src/services/horasServices.ts
  src/services/pontoServices.ts
Labels: bug, refactor

#90 Hotfix/skeleton
  src/middleware.ts
  src/pages/colaboradores/index.tsx
  src/pages/historico-ponto/[id].tsx
  src/pages/historico-ponto/index.tsx
  src/pages/inicio.tsx
  src/pages/inicioFuncionario/index.tsx
  src/pages/solicitacao/SolicitacaoCard/cardSkeleton.tsx
  src/pages/solicitacao/index.tsx
  src/pages/teste.tsx
Labels: bug

#96 Feat/tela banco horas
  package-lock.json
  package.json
  src/components/custom/InputBusca/inputBusca.tsx
  src/components/custom/Sidebar/app-sidebar.tsx
  src/components/custom/Sidebar/nav-secondary.tsx
  src/components/custom/TablePagination/TablePagination.tsx
  src/components/custom/tab/index.tsx
  src/components/custom/tab/styles.module.css
  src/components/ui/datatable.tsx
  src/components/ui/pagination.tsx
  src/components/ui/select.tsx
  src/interfaces/bancoHoras.ts
  src/lib/permissions.ts
  src/pages/bancoHoras/[id].tsx
  src/pages/bancoHoras/columns.tsx
  src/pages/bancoHoras/index.tsx
  src/pages/solicitacao/Solicitacao.module.css
  src/pages/solicitacao/index.tsx
  src/services/bancoHorasService.ts
  src/services/relatorioBancoHoras.ts
  src/services/setorService.ts
  src/utils/functions/calculateUserCargaMensal.ts
Labels: enhancement, task

#83 Hotfix: arrumando erros funcionais relativos a empresa
  src/components/custom/CadastroEmpresa/CadastroEmpresa.tsx
  src/pages/empresa/index.tsx
  src/pages/index.tsx
Labels: enhancement

#49 Hotfix/tela cadastro errors
  src/components/custom/CadastroEmpresa/CadastroEmpresa.tsx
  src/interfaces/empresa.ts
  src/pages/cadastro.tsx
Labels: bug, refactor

#97 feat/banco-horas-card
  package-lock.json
  package.json
  src/components/custom/histPonto/points-history-table.tsx
  src/components/ui/slider.tsx
  src/pages/historico-ponto/[id].tsx
  src/pages/historico-ponto/_components/CardBancoHoras/cardBancoHoras.tsx
  src/pages/historico-ponto/index.tsx
  src/services/bancoHorasService.ts
  src/services/extraPagaService.ts
  src/services/historicoCompensacaoService.ts
Labels: enhancement, task

#103 Feat/solicitacao ausencia
  package-lock.json
  src/components/custom/histPonto/points-history-table.tsx
  src/components/custom/histPonto/styles.module.css
  src/components/custom/modalSolicitacao/modalEnvioSolicitacaoFalta/index.tsx
  src/components/custom/modalSolicitacao/modalEnvioSolicitacaoFalta/styles.module.css
  src/components/custom/modalSolicitacao/modalJustificativaFalta/index.tsx
  src/components/custom/modalSolicitacao/modalJustificativaFalta/style.module.css
  src/interfaces/faltas.ts
  src/services/faltaService.ts
  src/utils/renderModalByTipoSolicitacao.tsx/index.tsx
Labels: enhancement

#102 hotfix: alteração de tabela Meus Pontos para correta exibição da coluna Observação
  src/components/custom/histPonto/points-history-table.tsx
  src/interfaces/Solicitacao.ts
Labels: enhancement

#101 feat: Adicionando card de horas mensais trabalhadas
  src/components/ui/select.tsx
  src/pages/_app.tsx
  src/pages/inicio.tsx
  src/pages/inicioFuncionario/_components/cardHorasTrabalhadas/cardHorasTrabalhadas.tsx
  src/pages/inicioFuncionario/_components/cardHorasTrabalhadas/styles.module.css
  src/pages/inicioFuncionario/_components/timeClock/time-clock.tsx
  src/pages/inicioFuncionario/index.tsx
Labels: enhancement

#112 Hotfix/solicitacao nivel acesso
  src/components/custom/tab/index.tsx
  src/pages/solicitacao/index.tsx
Labels: bug
